SRC				= main.cpp\
				addChar.cpp\
				openAndCheck.cpp\
				fillNewFile.cpp\

OBJS			= $(SRC:.cpp=.o)

CC			= c++

CCFLAGS	= -Wall -Wextra -Werror -std=c++98

NAME		= streamEdior

all : $(NAME)

$(NAME):$(OBJS)

	$(CC) $(OBJS) -o $(NAME)

clean :
	rm -rf $(OBJS)

fclean : clean
	rm -rf $(NAME)

re : fclean all